import type { NextPage } from 'next'
import Head from 'next/head'
import Login from '../components/Login'
import Header from '../components/Header'
import { useSession } from "next-auth/react"

const Home: NextPage = () => {

  const {data : session } = useSession()

  // If there is not a session display the login component
  if (!session) return <Login />

  return (
    <div >
      <Head>
        <title>SocialMeaps - Home </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div >

        {/* display the page components */}
        <Header />
      </div>
     
    </div>
  )
}

export default Home
