import type { NextPage } from 'next'
import Head from 'next/head'
import Login from '../components/Login'
import Header from '../components/Header'
import { useSession } from "next-auth/react"
import Link from 'next/link'

const Home: NextPage = () => {

  const {data : session } = useSession()

  // If there is not a session display the login component
  if (!session) return <Login />

  return (
    <div >
      <Head>
        <title>SocialMeaps - Home </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen h-screen">
        {/* display the page components */}
        <Header />
        <div className="grid grid-cols-4">
          {/* <Link href="/chat">
            <a className="col-span-1 col-start-2 p-5 m-5 text-2xl font-bold text-blue-600 rounded-md shadow-md"> Chat </a>
          </Link> */}
          <Link href="/calendar">
            <a className="col-span-1 col-start-3 p-5 m-5 text-2xl font-bold text-blue-600 rounded-md shadow-md"> Calendar </a>
          </Link>
        </div>
      </div>
     
    </div>
  )
}

export default Home
